Progress on handling network receive
Still has at least one issue (need to propagate taint properly for
assign within an anonymous function call), but committing now bc of this:
(haven't looked in detail, but suspect "no such process")

**** FAILURE
Server log:

config_tracing/delve master $ dlv exec --headless --api-version=2 --accept-multiclient --listen=:4040 ./network_recv
API server listening at: [::]:4040
2025-02-20T18:41:53-08:00 warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
ENTERING SYSCALL READ => ret to client
wp set for 0xc0000c0788 - not on stack
ENTER FAULTING SYSCALL syscall.read - arg: 0xc0000c0788
thread 1370431 (goroutine 20), syscall nil, arg nil
0x404661 in runtime/internal/syscall.Syscall6
 at /home/emily/projects/wtf_project/go1.20.1/src/runtime/internal/syscall/asm_linux_amd64.s:30
0x404653 in syscall.RawSyscall6
 at /home/emily/projects/wtf_project/go1.20.1/src/runtime/internal/syscall/syscall_linux.go:38
0x4c4785 in syscall.Syscall
 at /home/emily/projects/wtf_project/go1.20.1/src/syscall/syscall_linux.go:82
0x4c28ca in syscall.read
 at /home/emily/projects/wtf_project/go1.20.1/src/syscall/zsyscall_linux_amd64.go:711
0x4c0f8c in syscall.Read
 at /home/emily/projects/wtf_project/go1.20.1/src/syscall/syscall_unix.go:178
0x4e2078 in internal/poll.ignoringEINTRIO
 at /home/emily/projects/wtf_project/go1.20.1/src/internal/poll/fd_unix.go:794
0x4e0590 in internal/poll.(*FD).Read
 at /home/emily/projects/wtf_project/go1.20.1/src/internal/poll/fd_unix.go:163
0x528d59 in net.(*netFD).Read
 at /home/emily/projects/wtf_project/go1.20.1/src/net/fd_posix.go:55
0x53cd8a in net.(*conn).Read
 at /home/emily/projects/wtf_project/go1.20.1/src/net/net.go:183
0x5525ca in net.(*TCPConn).Read
 at <autogenerated>:1
0x65cf07 in main.main.func1
 at /home/emily/projects/config_tracing/delve/_fixtures/dlv_config_client/network_recv.go:28
0x4758c1 in runtime.goexit
 at /home/emily/projects/wtf_project/go1.20.1/src/runtime/asm_amd64.s:1598
thread 1370431 (goroutine 20), syscall nil, arg nil
no such process
ENTERING SYSCALL READ => ret to client
msg_copy: i

Client log:
config_tracing/delve master $ ./dlv_config_client -move_wps=false
Starting delve config client

CLIENT bp: &{ID:-4 Name:syscall-entry Addr:4212320 Addrs:[4212320] PreviousAddrs:[] AddrPid:[1370377] File:/home/emily/projects/wtf_project/go1.20.1/src/runtime/internal/syscall/asm_linux_amd64.s Line:30 FunctionName:runtime/internal/syscall.Syscall6 ExprString: Cond: HitCond: HitCondPerG:false Tracepoint:false TraceReturn:false Goroutine:false Stacktrace:0 Variables:[] LoadArgs:<nil> LoadLocals:<nil> WatchExpr: WatchType:0 WatchImpl:0 VerboseDescr:[] HitCount:map[] TotalHitCount:0 Disabled:false UserData:<nil> RootFuncName: TraceFollowCalls:0}
onSyscallEntryBpHit
2113584
5-tuple: 127.0.0.1:6060=>127.0.0.1:34524
CreateWatchpoint lineno 30 watchexpr p watchaddr 0xc0000c0788
	Memory-parameter map: 0xc0000c0788 => {params:{items:map[]} behaviors:{items:map[{behavior:{offset:0 local_endpoint:127.0.0.1:6060 remote_endpoint:127.0.0.1:34524 transport:tcp} flow:1}:{}]}}
	Memory-parameter map: 0xc0000c0789 => {params:{items:map[]} behaviors:{items:map[{behavior:{offset:1 local_endpoint:127.0.0.1:6060 remote_endpoint:127.0.0.1:34524 transport:tcp} flow:1}:{}]}}
	Memory-parameter map: 0xc0000c078a => {params:{items:map[]} behaviors:{items:map[{behavior:{offset:2 local_endpoint:127.0.0.1:6060 remote_endpoint:127.0.0.1:34524 transport:tcp} flow:1}:{}]}}
CLIENT bp: &{ID:-4 Name:syscall-entry Addr:4212320 Addrs:[4212320] PreviousAddrs:[] AddrPid:[1370377] File:/home/emily/projects/wtf_project/go1.20.1/src/runtime/internal/syscall/asm_linux_amd64.s Line:30 FunctionName:runtime/internal/syscall.Syscall6 ExprString: Cond: HitCond: HitCondPerG:false Tracepoint:false TraceReturn:false Goroutine:false Stacktrace:0 Variables:[] LoadArgs:<nil> LoadLocals:<nil> WatchExpr: WatchType:0 WatchImpl:0 VerboseDescr:[] HitCount:map[] TotalHitCount:0 Disabled:false UserData:<nil> RootFuncName: TraceFollowCalls:0}
onSyscallEntryBpHit
2113584
5-tuple: 127.0.0.1:6060=>127.0.0.1:34524
CreateWatchpoint lineno 30 watchexpr p watchaddr 0xc0000c0788
	Memory-parameter map: 0xc0000c0788 => {params:{items:map[]} behaviors:{items:map[{behavior:{offset:0 local_endpoint:127.0.0.1:6060 remote_endpoint:127.0.0.1:34524 transport:tcp} flow:1}:{}]}}
	Memory-parameter map: 0xc0000c0789 => {params:{items:map[]} behaviors:{items:map[{behavior:{offset:1 local_endpoint:127.0.0.1:6060 remote_endpoint:127.0.0.1:34524 transport:tcp} flow:1}:{}]}}
	Memory-parameter map: 0xc0000c078a => {params:{items:map[]} behaviors:{items:map[{behavior:{offset:2 local_endpoint:127.0.0.1:6060 remote_endpoint:127.0.0.1:34524 transport:tcp} flow:1}:{}]}}

**** (RELATIVE) SUCCESS:
Server log:
config_tracing/delve master $ dlv exec --headless --api-version=2 --accept-multiclient --listen=:4040 ./network_recv
API server listening at: [::]:4040
2025-02-20T19:03:14-08:00 warning layer=rpc Listening for remote connections (connections are not authenticated nor encrypted)
ENTERING SYSCALL READ => ret to client
wp set for 0xc0000200e0 - not on stack
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852096 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852092 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852096 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852092 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852092 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852092 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852096 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852092 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852092 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
ENTER FAULTING SYSCALL syscall.read - arg: 0xc0000200e0
thread 1379705 (goroutine 20), syscall nil, arg nil
0x404661 in runtime/internal/syscall.Syscall6
 at /home/emily/projects/wtf_project/go1.20.1/src/runtime/internal/syscall/asm_linux_amd64.s:30
0x404653 in syscall.RawSyscall6
 at /home/emily/projects/wtf_project/go1.20.1/src/runtime/internal/syscall/syscall_linux.go:38
0x4c4785 in syscall.Syscall
 at /home/emily/projects/wtf_project/go1.20.1/src/syscall/syscall_linux.go:82
0x4c28ca in syscall.read
 at /home/emily/projects/wtf_project/go1.20.1/src/syscall/zsyscall_linux_amd64.go:711
0x4c0f8c in syscall.Read
 at /home/emily/projects/wtf_project/go1.20.1/src/syscall/syscall_unix.go:178
0x4e2078 in internal/poll.ignoringEINTRIO
 at /home/emily/projects/wtf_project/go1.20.1/src/internal/poll/fd_unix.go:794
0x4e0590 in internal/poll.(*FD).Read
 at /home/emily/projects/wtf_project/go1.20.1/src/internal/poll/fd_unix.go:163
0x528d59 in net.(*netFD).Read
 at /home/emily/projects/wtf_project/go1.20.1/src/net/fd_posix.go:55
0x53cd8a in net.(*conn).Read
 at /home/emily/projects/wtf_project/go1.20.1/src/net/net.go:183
0x5525ca in net.(*TCPConn).Read
 at <autogenerated>:1
0x65cf07 in main.main.func1
 at /home/emily/projects/config_tracing/delve/_fixtures/dlv_config_client/network_recv.go:28
0x4758c1 in runtime.goexit
 at /home/emily/projects/wtf_project/go1.20.1/src/runtime/asm_amd64.s:1598
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852092 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852092 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING OTHER SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852128 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
Found buddy syscall (thread 1379705, syscall syscall.read, arg 0xc0000200e0) for segv thread 1379704 at 0xc0000200bc - won't stepInstruction
thread 1379705 has faultingSyscallArg 0xc0000200e0 - will step over entry bp
Found buddy syscall (thread 1379705, syscall syscall.read, arg 0xc0000200e0) for segv thread 1379676 at 0xc0000200bc - won't stepInstruction
handleSyscallExit
thread 1379705 (goroutine 20), syscall syscall.read, arg 0xc0000200e0
0x404674 in runtime/internal/syscall.Syscall6
 at /home/emily/projects/wtf_project/go1.20.1/src/runtime/internal/syscall/asm_linux_amd64.s:37
0x404653 in syscall.RawSyscall6
 at /home/emily/projects/wtf_project/go1.20.1/src/runtime/internal/syscall/syscall_linux.go:38
0x4c4785 in syscall.Syscall
 at /home/emily/projects/wtf_project/go1.20.1/src/syscall/syscall_linux.go:82
0x4c28ca in syscall.read
 at /home/emily/projects/wtf_project/go1.20.1/src/syscall/zsyscall_linux_amd64.go:711
0x4c0f8c in syscall.Read
 at /home/emily/projects/wtf_project/go1.20.1/src/syscall/syscall_unix.go:178
0x4e2078 in internal/poll.ignoringEINTRIO
 at /home/emily/projects/wtf_project/go1.20.1/src/internal/poll/fd_unix.go:794
0x4e0590 in internal/poll.(*FD).Read
 at /home/emily/projects/wtf_project/go1.20.1/src/internal/poll/fd_unix.go:163
0x528d59 in net.(*netFD).Read
 at /home/emily/projects/wtf_project/go1.20.1/src/net/fd_posix.go:55
0x53cd8a in net.(*conn).Read
 at /home/emily/projects/wtf_project/go1.20.1/src/net/net.go:183
0x5525ca in net.(*TCPConn).Read
 at <autogenerated>:1
0x65cf07 in main.main.func1
 at /home/emily/projects/config_tracing/delve/_fixtures/dlv_config_client/network_recv.go:28
0x4758c1 in runtime.goexit
 at /home/emily/projects/wtf_project/go1.20.1/src/runtime/asm_amd64.s:1598
EXIT FAULTING SYSCALL syscall.read - arg: 0xc0000200e0
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852096 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852092 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret fake bp from FindSoftwareWatchpoint: {FunctionName: File: Line:0 Addr:824633852096 PreviousAddrs:[] OriginalData:[] WatchExpr: WatchType:2 WatchImpl:1 SpuriousPageFault:true HWBreakIndex:0 watchStackOff:0 AlwaysToggleMprotect:false Breaklets:[] Logical:<nil> returnInfo:<nil> RootFuncName: TraceFollowCalls:0}
FAULTING NON-SYSCALL
ret real bp from FindSoftwareWatchpoint: Breakpoint 1 at 0xc0000200e0 :0

Client log:
config_tracing/delve master $ ./dlv_config_client -move_wps=false
Starting delve config client

CLIENT bp: &{ID:-4 Name:syscall-entry Addr:4212320 Addrs:[4212320] PreviousAddrs:[] AddrPid:[1379676] File:/home/emily/projects/wtf_project/go1.20.1/src/runtime/internal/syscall/asm_linux_amd64.s Line:30 FunctionName:runtime/internal/syscall.Syscall6 ExprString: Cond: HitCond: HitCondPerG:false Tracepoint:false TraceReturn:false Goroutine:false Stacktrace:0 Variables:[] LoadArgs:<nil> LoadLocals:<nil> WatchExpr: WatchType:0 WatchImpl:0 VerboseDescr:[] HitCount:map[] TotalHitCount:0 Disabled:false UserData:<nil> RootFuncName: TraceFollowCalls:0}
onSyscallEntryBpHit
2128042
5-tuple: 127.0.0.1:6060=>127.0.0.1:35646
CreateWatchpoint lineno 30 watchexpr p watchaddr 0xc0000200e0
	Memory-parameter map: 0xc0000200e0 => {params:{items:map[]} behaviors:{items:map[{behavior:{offset:0 local_endpoint:127.0.0.1:6060 remote_endpoint:127.0.0.1:35646 transport:tcp} flow:1}:{}]}}
	Memory-parameter map: 0xc0000200e1 => {params:{items:map[]} behaviors:{items:map[{behavior:{offset:1 local_endpoint:127.0.0.1:6060 remote_endpoint:127.0.0.1:35646 transport:tcp} flow:1}:{}]}}
	Memory-parameter map: 0xc0000200e2 => {params:{items:map[]} behaviors:{items:map[{behavior:{offset:2 local_endpoint:127.0.0.1:6060 remote_endpoint:127.0.0.1:35646 transport:tcp} flow:1}:{}]}}
CLIENT bp: &{ID:1 Name:p Addr:824633852128 Addrs:[824633852128] PreviousAddrs:[] AddrPid:[1379676] File: Line:0 FunctionName: ExprString: Cond: HitCond: HitCondPerG:false Tracepoint:false TraceReturn:false Goroutine:false Stacktrace:0 Variables:[] LoadArgs:<nil> LoadLocals:<nil> WatchExpr:p WatchType:51 WatchImpl:1 VerboseDescr:[] HitCount:map[20:1] TotalHitCount:1 Disabled:false UserData:<nil> RootFuncName: TraceFollowCalls:0}

*** Hit watchpoint for p
Location:
 /home/emily/projects/config_tracing/delve/_fixtures/dlv_config_client/network_recv.go:33 (0x65cf5e)
main.main.func1
msg_copy := recvd_msg[1] // wp hits for recvd_msg => propagate to msg_copy (on stack), m-c map should hv {&msg_copy} => 0x1
movzx ecx, byte ptr [rcx+0x1]
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
hit_line: 33
CallExpr; lines 17:35
linewithStmt
util.go:222: Error finding function func() {
	l, err := net.Listen("tcp", endpoint)
	if err != nil {
		panic(err)
	}
	conn, err := l.Accept()
	if err != nil {
		panic(err)
	}
	var recvd_msg [3]byte
	_, err = conn.Read(recvd_msg[:])
	if err != nil {
		panic(err)
	}
	msg_copy := recvd_msg[1]
	fmt.Printf("msg_copy: %v\n", string(msg_copy))
} in frame 0: Malformed breakpoint location "func() {\n\tl, err := net.Listen(\"tcp\", endpoint)\n\tif err != nil {\n\t\tpanic(err)\n\t}\n\tconn, err := l.Accept()\n\tif err != nil {\n\t\tpanic(err)\n\t}\n\tvar recvd_msg [3]byte\n\t_, err = conn.Read(recvd_msg[:])\n\tif err != nil {\n\t\tpanic(err)\n\t}\n\tmsg_copy := recvd_msg[1]\n\tfmt.Printf(\"msg_copy: %v\\n\", string(msg_copy))\n}" at 277: line offset negative or not a number